### ISSUE TITLE
Attachment bug on iPhone/iOS device (possibly other devices too)

### ISSUE THREAD

**Issue by RicheKicheR** [JonatanMGit/mr-sweet#32]
Hi I always fail to send an attachment through the attachment option on Mr. Sweet /say command but it works for other people please fix

Thx

Error message:
Application did not respond.

Replicate:

1. Go to a Discord server with Mr. Sweet bot
2. Use the /say command
3. Use the attachment option
4. Choose any image/video to your liking
5. Send message
![image](https://user-images.githubusercontent.com/131036843/232588105-343fe343-6fcb-4a10-9bdd-86d4040bbdcb.jpeg)

EDIT:

Okay so the video got sent seconds/minute later after the error message happened I think it's still a weird bug so fix asap

Thx

**Comment by JonatanMGit** [comment]
Can confirm on App: 175.7 (175207) canaryRelease; Manifest: N/A; Build Override: N/A; Device: vili (2107113SG) OS 31;

It seems like it is doing this randomly

**Comment by JonatanMGit** [comment]
<img width="378" alt="Image of a Dashboard showing a very slow Internet send and receive speeds" src="https://user-images.githubusercontent.com/60609358/232879303-414c0aa6-60e2-4086-9758-8fe1e18595f1.png">

This may be caused by the Mr Sweet Server having a weird network anomaly. It should be fixed anyways in https://github.com/JonatanMGit/mr-sweet/commit/59dee713e0e00f5d5b6883beda4d7ed73f72ef78
